#!/usr/bin/with-contenv bash

echo "**** installing apt-transport-https and dotnet ****"
apt-get update && \
  apt-get install -y wget apt-transport-https wget && \
  add-apt-repository universe
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O /tmp/packages-microsoft-prod.deb && \
  dpkg -i /tmp/packages-microsoft-prod.deb && \
  rm /tmp/packages-microsoft-prod.deb && \
apt-get update
  apt-get install -y dotnet-sdk-3.1
dotnet --info
